import { describe, it, expect, afterEach } from 'vitest';
import { existsSync, mkdirSync, mkdtempSync, readdirSync, readFileSync, rmSync, statSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { AppConfigSchema } from '../config/schema.js';
import { RuntimeResolver } from '../core/runtime-resolver.js';
import { memoryLayout, memorySettingsFor, type MemoryLayout } from './layout.js';
import { RECENT_MARKER, isRecentArtifact, lookbackDates, renderRecent, writeRecent } from './recent.js';
import { RecentMemory } from './recent-service.js';
import { snapshotMemoryDir } from '../journaling/memory-diff.js';

const NOW = new Date(2026, 9, 6, 15, 30); // local Oct 6, 2026

function layoutWith(overrides: Partial<MemoryLayout> = {}): MemoryLayout {
  return { ...memoryLayout({ agentId: 'agent:x', source: 'default', dir: 'memory', indexFile: 'MEMORY.md', dailySubdir: 'daily', lookbackDays: 3, recentBudgetChars: 20_000, native: true }, '/w'), ...overrides };
}

const reader = (files: Record<string, string>) => (date: string) => files[date] ?? null;

let dir: string | null = null;
afterEach(() => {
  if (dir) rmSync(dir, { recursive: true, force: true });
  dir = null;
});

describe('recent.md rendering (E67 S67.2)', () => {
  it('lists local dates newest first', () => {
    expect(lookbackDates(NOW, 3)).toEqual(['2026-10-06', '2026-10-05', '2026-10-04']);
    expect(lookbackDates(new Date(2026, 2, 1, 0, 5), 2)).toEqual(['2026-03-01', '2026-02-28']);
    expect(lookbackDates(NOW, 0)).toEqual([]);
  });

  it('renders newest first behind the generated header, skipping missing days', () => {
    const r = renderRecent(layoutWith(), NOW, reader({ '2026-10-06': 'today stuff', '2026-10-04': 'older stuff' }));
    expect(r.content.startsWith(RECENT_MARKER)).toBe(true);
    expect(r.content).toContain('Do not edit this file');
    expect(r.content.indexOf('## 2026-10-06 (today)')).toBeLessThan(r.content.indexOf('## 2026-10-04'));
    expect(r.content).not.toContain('2026-10-05');
    expect(r.days.map((d) => d.date)).toEqual(['2026-10-06', '2026-10-04']);
    expect(r.truncated).toBe(false);
  });

  it('says so when there are no dailies', () => {
    const r = renderRecent(layoutWith(), NOW, reader({}));
    expect(r.content).toContain('No daily journal entries in the last 3 day(s).');
    expect(r.days).toEqual([]);
  });

  it('keeps the whole file within budget: the end of the newest day that does not fit, then a marker', () => {
    const today = Array.from({ length: 50 }, (_, i) => `- entry ${i} ${'x'.repeat(40)}`).join('\n');
    const older = 'y'.repeat(800);
    const layout = layoutWith({ recentBudgetChars: 1500 });
    const r = renderRecent(layout, NOW, reader({ '2026-10-06': today, '2026-10-05': older }));
    expect(r.content.length).toBeLessThanOrEqual(1500);
    expect(r.truncated).toBe(true);
    expect(r.days).toEqual([expect.objectContaining({ date: '2026-10-06', truncated: true })]);
    expect(r.content).toContain('- entry 49'); // the latest entries survive
    expect(r.content).not.toContain('- entry 0 ');
    expect(r.content).toContain('Earlier entries of this day were cut');
    expect(r.omitted).toEqual(['2026-10-05']);
    expect(r.content).toContain('1 older day(s) left out to fit the 1500-character budget: `memory/daily/2026-10-05.md`');
  });

  it('includes whole days while they fit and omits the rest', () => {
    const layout = layoutWith({ recentBudgetChars: 1000 });
    const r = renderRecent(layout, NOW, reader({ '2026-10-06': 'a'.repeat(100), '2026-10-05': 'b'.repeat(100), '2026-10-04': 'c'.repeat(2000) }));
    expect(r.days.map((d) => d.date)).toEqual(['2026-10-06', '2026-10-05', '2026-10-04']);
    expect(r.days[2]!.truncated).toBe(true);
    expect(r.content.length).toBeLessThanOrEqual(1000);
  });

  it('is stable for unchanged input and follows the date rollover', () => {
    const files = { '2026-10-06': 'today stuff' };
    expect(renderRecent(layoutWith(), NOW, reader(files)).content).toBe(renderRecent(layoutWith(), NOW, reader(files)).content);
    const tomorrow = renderRecent(layoutWith(), new Date(2026, 9, 7, 0, 1), reader(files));
    expect(tomorrow.content).toContain('## 2026-10-06\n');
    expect(tomorrow.content).not.toContain('(today)');
    const later = renderRecent(layoutWith(), new Date(2026, 9, 9, 0, 1), reader(files));
    expect(later.days).toEqual([]);
  });
});

describe('writeRecent', () => {
  function setup(): MemoryLayout {
    dir = mkdtempSync(join(tmpdir(), 'recent-'));
    mkdirSync(join(dir, 'memory', 'daily'), { recursive: true });
    writeFileSync(join(dir, 'memory', 'daily', '2026-10-06.md'), '# Oct 6\n- did a thing\n');
    return memoryLayout(memorySettingsFor(AppConfigSchema.parse({ bus: { db_path: ':memory:' }, adapters: {}, memory: {} }), 'x'), dir);
  }

  it('writes atomically, then reports unchanged without touching the file', () => {
    const layout = setup();
    const first = writeRecent(layout, NOW);
    expect(first.status).toBe('written');
    expect(readFileSync(layout.recentPath!, 'utf-8')).toContain('- did a thing');
    expect(readdirSync(layout.memoryDir!).filter((f) => f.includes('.tmp-'))).toEqual([]);
    const mtime = statSync(layout.recentPath!).mtimeMs;
    const second = writeRecent(layout, NOW);
    expect(second.status).toBe('unchanged');
    expect(second.hash).toBe(first.hash);
    expect(statSync(layout.recentPath!).mtimeMs).toBe(mtime);
  });

  it('skips an agent whose memory dir does not exist (never creates it)', () => {
    dir = mkdtempSync(join(tmpdir(), 'recent-'));
    const layout = memoryLayout(memorySettingsFor(AppConfigSchema.parse({ bus: { db_path: ':memory:' }, adapters: {}, memory: {} }), 'x'), dir);
    expect(writeRecent(layout, NOW).status).toBe('skipped');
    expect(existsSync(join(dir, 'memory'))).toBe(false);
  });

  it('recent.md is left out of journal memory diffs', () => {
    const layout = setup();
    writeRecent(layout, NOW);
    expect(isRecentArtifact('recent.md')).toBe(true);
    expect(isRecentArtifact('daily/recent.md')).toBe(false);
    expect([...snapshotMemoryDir(layout.memoryDir)!.keys()]).toEqual(['daily/2026-10-06.md']);
  });
});

describe('RecentMemory service', () => {
  it('regenerates every agent at startup and again when the local date changes', () => {
    dir = mkdtempSync(join(tmpdir(), 'recent-svc-'));
    mkdirSync(join(dir, 'memory', 'daily'), { recursive: true });
    writeFileSync(join(dir, 'memory', 'daily', '2026-10-06.md'), 'entry');
    const config = AppConfigSchema.parse({
      bus: { db_path: ':memory:' },
      adapters: { 'cc-pool': { agent_id: 'peggy', tmux_session: 'p', claude_bin: '/usr/local/bin/claude', working_dir: dir } },
      memory: {},
    });
    let now = NOW;
    const logs: string[] = [];
    const svc = new RecentMemory({ config, resolver: new RuntimeResolver(config), now: () => now, log: (l) => logs.push(l) });
    svc.regenerateAll('startup');
    const path = join(dir, 'memory', 'recent.md');
    expect(readFileSync(path, 'utf-8')).toContain('## 2026-10-06 (today)');
    svc.tick(); // same day: nothing
    expect(logs.filter((l) => l.includes('regenerated'))).toHaveLength(1);
    now = new Date(2026, 9, 7, 0, 0, 30);
    svc.tick();
    expect(readFileSync(path, 'utf-8')).toContain('## 2026-10-06\n');
    expect(logs.at(-1)).toContain('(midnight;');
    expect(svc.regenerate('agent:peggy-pool-1', 'journaled').status).toBe('unchanged');
  });
});

describe('journaler prompts mention recent.md', () => {
  it('names the path relative to the working dir', async () => {
    const { recentNotice } = await import('../journaling/prompt.js');
    expect(recentNotice({ workingDir: '/w', memoryDir: '/w/notes' })).toContain('Do not edit notes/recent.md');
    expect(recentNotice({ workingDir: null, memoryDir: null })).toContain('memory/recent.md');
  });
});
