/**
 * `recent.md` generator (E67 S67.2). See docs/AGENT_MEMORY.md#recentmd.
 *
 * Claude Code's native memory has no notion of daily journals, so the bus
 * keeps `<memory dir>/recent.md`: the last `lookback_days` of dailies (local
 * dates), newest first, within `recent_budget_chars`, behind a "generated, do
 * not edit" header. The agent's `CLAUDE.md` imports it (`@memory/recent.md`).
 *
 * The output depends only on the daily files and the local date (no
 * timestamps), so regenerating without a change writes nothing and the
 * freshness hook's content hash stays put.
 */
import { createHash, randomBytes } from 'node:crypto';
import { readFileSync, renameSync, statSync, unlinkSync, writeFileSync } from 'node:fs';
import { basename, join } from 'node:path';
import { formatLocalDate } from '../adapters/memory-context.js';
import { RECENT_FILE, dailyPath, type MemoryLayout } from './layout.js';

/** First line of every generated file; also how the setup check recognizes one. */
export const RECENT_MARKER = '<!-- Generated by AgentBus (memory/recent.md). Do not edit: it is rewritten after every journal run and at local midnight. -->';
/** A partial day keeps at least this much of its tail; less than that and the day is omitted instead. */
const MIN_PARTIAL_CHARS = 200;

export type RecentLayout = Pick<MemoryLayout, 'dir' | 'dailySubdir' | 'dailyDir' | 'lookbackDays' | 'recentBudgetChars'>;

export interface RecentDay {
  date: string;
  /** Characters of the day's journal included. */
  chars: number;
  /** Only the end of the day's journal fit. */
  truncated: boolean;
}

export interface RecentRender {
  content: string;
  /** Days included, newest first. */
  days: RecentDay[];
  /** Days that had a journal but didn't fit, newest first. */
  omitted: string[];
  truncated: boolean;
}

/** `days` local dates ending today, newest first. */
export function lookbackDates(now: Date, days: number): string[] {
  const out: string[] = [];
  for (let i = 0; i < days; i++) {
    const d = new Date(now);
    d.setDate(d.getDate() - i);
    out.push(formatLocalDate(d));
  }
  return out;
}

function readDaily(path: string | null): string | null {
  if (!path) return null;
  try {
    const text = readFileSync(path, 'utf-8').trim();
    return text.length > 0 ? text : null;
  } catch {
    return null;
  }
}

/** The last `max` characters of `text`, starting at a line boundary when one is near. */
function tailOf(text: string, max: number): string {
  if (text.length <= max) return text;
  const cut = text.slice(text.length - max);
  const nl = cut.indexOf('\n');
  return nl >= 0 && nl < cut.length - 1 ? cut.slice(nl + 1) : cut;
}

/**
 * Render `recent.md` for `now`. `read` is injectable for tests; by default
 * the daily files are read from `layout.dailyDir`. The whole file, header
 * and markers included, stays within `recentBudgetChars`.
 */
export function renderRecent(layout: RecentLayout, now: Date, read: (date: string) => string | null = (date) => readDaily(dailyPath(layout, date))): RecentRender {
  const dailyRel = `${layout.dir.replace(/\/+$/, '')}/${layout.dailySubdir}`;
  const budgetChars = layout.recentBudgetChars;
  const budget = budgetChars - 1; // room for the final newline
  const today = formatLocalDate(now);
  const header = [
    RECENT_MARKER,
    '# Recent journal',
    '',
    `_The last ${layout.lookbackDays} day(s) of daily journals from \`${dailyRel}/\`, newest first, generated by AgentBus. ` +
      'Do not edit this file: write to the daily journal instead._',
  ].join('\n');

  const available = lookbackDates(now, layout.lookbackDays)
    .map((date) => ({ date, text: read(date) }))
    .filter((d): d is { date: string; text: string } => d.text !== null);

  const omittedMarker = (dates: string[]) =>
    `\n\n_[${dates.length} older day(s) left out to fit the ${budgetChars}-character budget: ` +
    `${dates.map((d) => `\`${dailyRel}/${d}.md\``).join(', ')}.]_`;

  let content = header;
  const days: RecentDay[] = [];
  const omitted: string[] = [];
  let truncated = false;

  for (let i = 0; i < available.length; i++) {
    const { date, text } = available[i]!;
    const heading = `\n\n## ${date}${date === today ? ' (today)' : ''}\n\n`;
    const rest = available.slice(i + 1).map((d) => d.date);
    const reserve = rest.length > 0 ? omittedMarker(rest).length : 0;
    if (content.length + heading.length + text.length + reserve <= budget) {
      content += heading + text;
      days.push({ date, chars: text.length, truncated: false });
      continue;
    }
    // Doesn't fit: keep the end of this day (its latest entries) if enough room is left.
    truncated = true;
    const cutNote = `_[Earlier entries of this day were cut to fit the budget; the full journal is \`${dailyRel}/${date}.md\`.]_\n\n`;
    const leftOut = available.slice(i + 1).map((d) => d.date);
    const room = budget - content.length - heading.length - cutNote.length - (leftOut.length > 0 ? omittedMarker(leftOut).length : 0);
    if (room >= MIN_PARTIAL_CHARS) {
      const tail = tailOf(text, room);
      content += heading + cutNote + tail;
      days.push({ date, chars: tail.length, truncated: true });
      omitted.push(...leftOut);
    } else {
      omitted.push(date, ...leftOut);
    }
    break;
  }

  if (available.length === 0) {
    content += `\n\n_No daily journal entries in the last ${layout.lookbackDays} day(s)._`;
  }
  if (omitted.length > 0) content += omittedMarker(omitted);
  // Safety net for pathological inputs (huge dates list in a tiny budget).
  if (content.length > budget) content = content.slice(0, budget);
  return { content: `${content}\n`, days, omitted, truncated };
}

export function hashContent(content: string): string {
  return createHash('sha256').update(content, 'utf-8').digest('hex');
}

export interface RecentWriteResult {
  status: 'written' | 'unchanged' | 'skipped';
  path: string | null;
  /** Why it was skipped. */
  reason?: string;
  /** sha256 of the file content (unset when skipped). */
  hash?: string;
  render?: RecentRender;
}

function isDir(path: string | null): boolean {
  if (!path) return false;
  try {
    return statSync(path).isDirectory();
  } catch {
    return false;
  }
}

/**
 * Regenerate `<memory dir>/recent.md`. Skipped when the memory dir doesn't
 * exist (the agent isn't set up; the bus never creates it). Writes only when
 * the content changed, atomically (temp file in the same dir, then rename).
 */
export function writeRecent(layout: RecentLayout & Pick<MemoryLayout, 'memoryDir' | 'recentPath'>, now: Date): RecentWriteResult {
  if (!layout.memoryDir || !layout.recentPath) return { status: 'skipped', path: null, reason: 'no memory dir (relative dir and no working dir)' };
  if (!isDir(layout.memoryDir)) return { status: 'skipped', path: layout.recentPath, reason: `memory dir ${layout.memoryDir} does not exist` };
  const render = renderRecent(layout, now);
  const hash = hashContent(render.content);
  let current: string | null = null;
  try {
    current = readFileSync(layout.recentPath, 'utf-8');
  } catch {
    current = null;
  }
  if (current === render.content) return { status: 'unchanged', path: layout.recentPath, hash, render };
  const tmp = join(layout.memoryDir, `.${basename(RECENT_FILE)}.tmp-${process.pid}-${randomBytes(4).toString('hex')}`);
  try {
    writeFileSync(tmp, render.content, 'utf-8');
    renameSync(tmp, layout.recentPath);
  } catch (err) {
    try { unlinkSync(tmp); } catch { /* already gone */ }
    throw err;
  }
  return { status: 'written', path: layout.recentPath, hash, render };
}

/** True for `recent.md` and its temp files, relative to the memory dir (excluded from journal memory diffs). */
export function isRecentArtifact(relPath: string): boolean {
  return relPath === RECENT_FILE || /^\.recent\.md\.tmp-/.test(relPath);
}
